spring.application.name=medilabo-gateway
server.port=8085
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=DEBUG
spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=servlet
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
jwt.secret=hste39h@01maLqP09182naheyd517809
jwt.expiration=3600
spring.cloud.gateway.routes[0].id=frontend
spring.cloud.gateway.routes[0].uri=http://medilabo-frontend:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/ui/**
spring.cloud.gateway.routes[1].id=patient-service
spring.cloud.gateway.routes[1].uri=http://medilabo-demographics:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/patient/**
spring.cloud.gateway.routes[2].id=history-service
spring.cloud.gateway.routes[2].uri=http://medilabo-physiciannotes:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/history/**
spring.cloud.gateway.routes[3].id=diabetes-service
spring.cloud.gateway.routes[3].uri=http://medilabo-determindiabetes:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/diabetes/**